### ISSUE TITLE
Not exist Variables when post mutation

### ISSUE THREAD

**Issue by nmquaan** [s12v/graphql-devtools#3]
![asdasdasd](https://user-images.githubusercontent.com/10013851/41267033-08c9ddb0-6e24-11e8-96bf-4064a3d0a6a4.png)
I have submit a request mutation but when /graphql-devtools capture request not exist variables in tab Variables. Please help me resolve it. 
This tool is useful

**Comment by alexbusu** [comment]
Same for me. For all queries.
It is expected `variables` parameter to be string.
![image](https://user-images.githubusercontent.com/4104165/47091021-fa4b7800-d21b-11e8-8e02-5fa81490e5f0.png)
Which, in my case, is JSON.
![image](https://user-images.githubusercontent.com/4104165/47091180-3e3e7d00-d21c-11e8-9e69-ad517283a0b7.png)

It would be nice to test the format before trying to convert the supposedly String value.

**Comment by nmquaan** [comment]
Hi @alexbusu,
Thanks for your feedback.
Please provide information about the release to the Google Chrome store

**Comment by nmquaan** [comment]
hi @alexbusu,
Can you create one more button to remove all requests similar to Chrome's Network Tab?
Thanks for your support!

**Comment by sasselin** [comment]
Same here with 76.0.3809.100 (Official Build) (64-bit)

The variables do not show in tab.

**Comment by esatterwhite** [comment]
Same version 0.1.2

**Comment by sharshuv-quotient** [comment]
+1 for that. There seem to be no GraphQL plugin without a bug...

**Comment by s12v** [comment]
Fixed in v1.0.0 — variables are shown whether they arrive as an object or as a JSON string. The fix from #4 finally ships; sorry it took this long. There is also a Clear button now, as asked in this thread.

Until the Web Store listing is back, load it unpacked from `master` or the zip at https://github.com/s12v/graphql-devtools/releases/tag/v1.0.0.

(AI-generated)
